### ISSUE TITLE
[Linux] desktop file is lacking a Categories= entry

### ISSUE THREAD

**Issue by probonopd** [mki1967/mki3dgame#1]
The desktop file is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).

Reference: https://github.com/AppImage/AppImageHub/issues/2

**Comment by mki1967** [comment]
I have been trying to add  some metainfo as suggested by appimagetool, but now it fails. Where should I place the mki3d.desktop file?
I have committed current state to branch 'unstable':

commit ab03aec79ec88f7834b9ce91d4f2efa3b5d01289
Author: Marcin Kik <mki1967@gmail.com>
Date:   Sat Aug 19 17:49:39 2017 +0200

    trying to add metainfo, but  creating appImage now fails:
    
    $ appimagetool-x86_64.AppImage mki3dgame
    Arch: 86_64
    /home/kik/go/src/github.com/mki1967/mki3dgame should be packaged as mki3dgame-x86_64.AppImage
    AppStream upstream metadata found in usr/share/metainfo/mki3dgame.appdata.xml
    E - mki3dgame.appdata.xml:mki3dgame.desktop
        Component metadata refers to a non-existing .desktop file.
    
    Validation failed.
    Failed to validate AppStream information with appstreamcli

**Comment by probonopd** [comment]
Inside the AppDir, `usr/share/applications/mki3d.desktop` would be the usual location.
Does it work then?

**Comment by mki1967** [comment]
First I moved mki3d.desktop:
$ mkdir usr/share/applications/
$ git mv mki3dgame.desktop usr/share/applications/

But then the file was missing in the main directory:
$ appimagetool-x86_64.AppImage mki3dgame
$ID.desktop file not found

Then I made a copy back to the main directory:
$ cp usr/share/applications/mki3dgame.desktop .
And it worked:
$ appimagetool-x86_64.AppImage mki3dgame
Arch: 86_64
...
Success

Finally I replaced the last copy with symbolic link. 
I have made a release v1.4 with attached binary file mki3dgame-x86_64.AppImage. 
I hope it is now correct?

**Comment by probonopd** [comment]
Yes that sounds very good, testing now. Thank you.

**Comment by probonopd** [comment]
Sent a PR, https://github.com/mki1967/mki3dgame/pull/2

**Comment by mki1967** [comment]
I have merged the PR and made the release v1.5 with new AppImage.

**Comment by mki1967** [comment]
Thank you for your help in solving the problem. 
Should I close the issue now?

**Comment by probonopd** [comment]
Yes, this can be closed now. Thank you very much.
