### ISSUE TITLE
Please provide AppImage for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [mki1967/mki3dgame#3]
> You can also prepare your own AppImage for Linux as described in https://github.com/mki1967/mki3dgame/blob/master/appImage-instructions.txt

Please provide an AppImage for download on GitHub Releases. You can use [Travis CI](https://travis-ci.org/) to automate this.

Doing so would make it possible to include it in the [AppImageHub central directory of available AppImages](https://appimage.github.io/apps/).

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by mki1967** [comment]
@probonopd I am preparing AppImage for each release by running the script:
https://github.com/mki1967/mki3dgame/blob/master/make-AppImage.bash
in the main directory, and then I upload it as attached binaries to the release creation page:
https://github.com/mki1967/mki3dgame/releases/new

For example, the AppImage for the most recent release is available at:
https://github.com/mki1967/mki3dgame/releases/download/v1.9/mki3dgame-x86_64.AppImage

Is there any other place, where I should upload the file?

**Comment by probonopd** [comment]
Must have overlooked it. Thank you very much!

**Comment by probonopd** [comment]
Strangely getting this message:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/7c86c8a65877d091a6723018a102667711a40beb/database/mki3dgame/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/154

Not sure what causes this, though.

**Comment by mki1967** [comment]
I was testing the AppImage on desktops and laptops with Ubuntu 16.04 LTS and on Manjaro that I have on my protable disk.
I could not reproduce this error. 
Was this error on some older version of the Linux system?

The panic seems to be raised when the GLFW window is created:
`   112         window, err := glfw.CreateWindow(windowWidth, windowHeight, "Mki3dgame", nil, nil)`
 `  113         if err != nil {`
 `  114                 panic(err)`
 `   115         }`

However, your message helped me to notice that I have somehow accidentally reinstalled and used the older version of Go -- the one from distribution :-/  

I have now prepared the AppImage compiled again with: go version go1.8.3 linux/amd64
https://github.com/mki1967/mki3dgame/releases/download/v1.9.2/mki3dgame-x86_64.AppImage

**Comment by probonopd** [comment]
Yes, I am using the oldest still-supported LTS release which is 14.04 at this point.

**Comment by mki1967** [comment]
I do not have access to Ubuntu 14.04 at this moment. 
I am using the OpenGL version 3.3 which is the oldest worth to be used according to:
 https://learnopengl.com/#!Getting-started/OpenGL
Maybe the required profile is not available on Ubuntu 14.04?

    107         glfw.WindowHint(glfw.ContextVersionMajor, 3)
    108         glfw.WindowHint(glfw.ContextVersionMinor, 3)
    109         glfw.WindowHint(glfw.OpenGLProfile, glfw.OpenGLCoreProfile)
    110         glfw.WindowHint(glfw.OpenGLForwardCompatible, glfw.True)
    111         glfw.WindowHint(glfw.Samples, 4) // try multisampling for better quality ...
    112         window, err := glfw.CreateWindow(windowWidth, windowHeight, "Mki3dgame", nil, nil)
    113         if err != nil {
    114                 panic(err)
    115         }

```

**Comment by probonopd** [comment]
Quite possibly.

**Comment by mki1967** [comment]
@probonopd  I have commented out the line with the GLFW hint for Forward Compatibility:
`    110         // glfw.WindowHint(glfw.OpenGLForwardCompatible, glfw.True)
`
I have made a new release 
https://github.com/mki1967/mki3dgame/releases/tag/v1.9.3
with this AppImage:
https://github.com/mki1967/mki3dgame/releases/download/v1.9.3/mki3dgame-x86_64.AppImage

I have tested that this AppImage still works on Ubuntu 16.04 and on Manjaro and I hope it should also work on Ubuntu 14.04 (since the error message on the picture  mentioned 'Forward compatibility')

**Comment by probonopd** [comment]
Now getting

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/6ec2fa07199bf095c603650861f47eedec46a141/database/mki3dgame/screenshot.png)

But this may be due to the fact that there is no proper OpenGL on my test setup.

**Comment by mki1967** [comment]
Maybe I should install Ubuntu 14.04 on some USB stick ...
I have just started downloading:
 http://releases.ubuntu.com/14.04/ubuntu-14.04.5-desktop-amd64.iso.torrent?_ga=2.258831938.959726710.1510128452-1353750228.1508527019
form the page:
https://www.ubuntu.com/download/alternative-downloads

I hope it is the proper version?

**Comment by mki1967** [comment]
I have started the downloaded Ubunu 14.04.5 in VirtualBox, 
then I have downloaded the AppImage:
https://github.com/mki1967/mki3dgame/releases/download/v1.9.3/mki3dgame-x86_64.AppImage
And it works! 

![zrzut ekranu z 2017-11-08 10-06-51](https://user-images.githubusercontent.com/4190247/32540390-e2aba070-c46c-11e7-9476-3b5f6bcb9bc6.png)

Now I have no idea what should I do ...

**Comment by probonopd** [comment]
Thank you very much. So it indeed seems to be an issue of my automated test setup. Sorry for having created noise here.

**Comment by mki1967** [comment]
@probonopd   I have just started to use (and to learn) Travis today. 

Without much understanding, I have used slightly modified version of 
https://github.com/go-gl/example/blob/master/.travis.yml
in mki3dgame as  
https://github.com/mki1967/mki3dgame/blob/master/.travis.yml
and the build passed. 

Maybe the following fragment is a hint for the needed setup:
 ```
addons:
  apt_packages:
    - libgl1-mesa-dev
    - xorg-dev

```

**Comment by probonopd** [comment]
You mean, for the build or for running the test @mki1967?

**Comment by mki1967** [comment]
The '-dev' libs are for build. Three related runtime code should be in standard desktop environment. The appimage from my releases run on the desktops that's I have tested.

**Comment by probonopd** [comment]
OK, so the only question then is why are we seeing this error on the machine that does the automated reviews and screenshots. If I merge this as-is, then the ugly error will be on the screenshot on AppImageHub, which is not desirable. Would you consider adding an AppStream file including a link to a pretty screenshot? Thanks.

Here is an AppStream assistant that should make it easy:
http://output.jsbin.com/qoqukof

**Comment by mki1967** [comment]
Ok. I will try to work 
on  it.

**Comment by mki1967** [comment]
@probonopd 

I have prepared the file `usr/share/metainfo/mki3dgame.appdata.xml` with the page and now I get the following strange error, while building the AppImage with `appimagetool-x86_64.AppImage`:
```
Building AppImage ...
Using architecture x86_64
/home/kik/go/src/github.com/mki1967/mki3dgame/build-AppImage/mki3dgame should be packaged as mki3dgame-x86_64.AppImage
AppStream upstream metadata found in usr/share/metainfo/mki3dgame.appdata.xml

(appstreamcli:14112): GLib-ERROR **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmem.c:100: failed to allocate 18446744073677196177 bytes
Trace/breakpoint trap (core dumped)
Failed to validate AppStream information with appstreamcli
```
I have pushed the (culprit?) file to master branch:
[mki3dgame.appdata.xml](https://github.com/mki1967/mki3dgame/blob/master/usr/share/metainfo/mki3dgame.appdata.xml)

The [previous version](https://github.com/mki1967/mki3dgame/blob/unstable/usr/share/metainfo/mki3dgame.appdata.xml)
did not cause such problem.

**Comment by probonopd** [comment]
Interesting @mki1967. So `appstreamcli` is crashing?

This is what I am getting on Deepin Linux:

```
me@host:~/AppImageKit/build$ appstreamcli validate /home/me/Downloads/mki3dgame.appdata.xml 
W - mki3dgame.appdata.xml:mki3dgame:12
    Found invalid tag: 'launchable'. Non-standard tags must be prefixed with "x-".

I - mki3dgame.appdata.xml:mki3dgame:9
    First 'description/p' paragraph might be too short (< 80 characters).

W - mki3dgame.appdata.xml:mki3dgame:3
    The component ID is not a reverse domain-name. Please update the ID and that of 
    the accompanying .desktop file to follow the latest version of the Desktop-Entry 
    and AppStream specifications and avoid future issues.

W - mki3dgame.appdata.xml:mki3dgame:4
    The metadata itself does not seem to be licensed under a permissive license. 
    Please license the data under a permissive license, like FSFAP, CC-0-1.0 or MIT to 
    allow distributors to include it in mixed data collections without the risk of 
    license violations due to mutually incompatible licenses.

Validation failed: warnings: 3, infos: 1
```

@ximion: I'm pretty sure I didn't invent the tag 'launchable'...

**Comment by ximion** [comment]
@probonopd You didn't - what's the version of AppStream you use to validate this? `appstreamcli --version` should ideally return something like `AppStream version: 0.11.8`

**Comment by probonopd** [comment]
```
appstreamcli --version
AppStream CLI tool version: 0.11.2
```

That is the latest version in my distribution, `deepin-15.5-amd64.iso`. You see, we need a way to bring the latest version to people (static build, AppImage, web service, whatever...)

**Comment by ximion** [comment]
Heh, yeah, the smallest version you would need for this to validate properly is `0.11.3` (released beginning of last August).

**Comment by mki1967** [comment]
The version of `appstreamcli` on my Ubuntu 16.04 is:
```
$ appstreamcli --version
AppStream CLI tool version: 0.9.4

```
Maybe the most recent version of `appstreamcli` could be bundled to `appimagetool-x86_64.AppImage` ?

**Comment by probonopd** [comment]
It has been an ongoing systematic ongoing annoyance that it is hard to run the latest appstreamcli on the oldest still-supported LTS releases of distributions (the ones we recommend for compiling applications on, to get binary compatibility with older systems). 

We have a more recent version of `appstreamcli` at https://github.com/AppImage/appimage.github.io/releases/download/deps/appstreamcli-x86_64.AppImage - would this work for you?

**Comment by mki1967** [comment]
I have build the last  [mki3dgame-x86_64.AppImage](https://github.com/mki1967/mki3dgame/releases/download/v1.14/mki3dgame-x86_64.AppImage) with the recent  [appimagetool-x86_64.AppImage](https://github.com/AppImage/AppImageKit/releases/download/10/appimagetool-x86_64.AppImage) on Ubuntu 18.04 and it seems to be ok. Even the icon is being displayed while the program is running ;-)

I have noticed that the file:
https://github.com/AppImage/appimage.github.io/blob/master/database/mki3dgame/mki3dgame.appdata.xml
is from 7 Nov 2017.  The current version is:
https://github.com/mki1967/mki3dgame/blob/master/usr/share/metainfo/io.github.mki1967.mki3dgame.appdata.xml
